### ISSUE TITLE
antidote tries to clone local package declarations from github

### ISSUE THREAD

**Issue by soupersauce** [mattmc3/antidote#98]
```
 antidote cloning ~/.fzf/shell/...
# antidote cloning ~/.config/zsh/zshrc.d/...
remote: Please upgrade your git client.
remote: GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
fatal: unable to access 'https://github.com/~/.fzf/shell/': The requested URL returned error: 403
remote: Please upgrade your git client.
remote: GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
fatal: unable to access 'https://github.com/~/.config/zsh/zshrc.d/': The requested URL returned error: 403
remote: Please upgrade your git client.
remote: GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
fatal: unable to access 'https://github.com/~/.fzf/shell/': The requested URL returned error: 403
antidote: error: bundle path not found '/home/.../.cache/antidote/.fzf/shell'
```

```
echo $ZSH_VERSION
5.8.1
```

**Comment by mattmc3** [comment]
This is a timely bug report. Thanks for submitting it. I was just working on the 1.7.3 release and had already fixed this issue. I was going to put more features in before cutting a release, but since this is affecting someone right now, I'll push those out to 1.7.4 and publish. This should work now if you run `antidote update`.

**Comment by soupersauce** [comment]
Much appreciated.

**Comment by razvanazamfirei** [comment]
This is a follow-up on the fix. The plugins get attached, but it still throws up errors. 
```
 # Clear local plugins from zsh_plugins.txt
 ~ antidote load
 ~ exec zsh
 # Add local plugins back
 ~ antidote load
# antidote cloning $ZDOTDIR/plugins/brew...
# antidote cloning $ZDOTDIR/plugins/python...
# antidote cloning $ZDOTDIR/plugins/utility...
# antidote cloning $ZDOTDIR/plugins/xdg-basedir...
remote: Not Found
fatal: repository 'https://github.com/$ZDOTDIR/plugins/utility/' not found
remote: Not Found
fatal: repository 'https://github.com/$ZDOTDIR/plugins/brew/' not found
remote: Not Found
fatal: repository 'https://github.com/$ZDOTDIR/plugins/xdg-basedir/' not found
remote: Not Found
fatal: repository 'https://github.com/$ZDOTDIR/plugins/python/' not found
# antidote cloning $ZDOTDIR/plugins/brew...
remote: Not Found
fatal: repository 'https://github.com/$ZDOTDIR/plugins/brew/' not found
antidote: error: bundle path not found '/Users/johnqpublic/.config/zsh/.antidote/.plugins/plugins/brew'.
 ~ exec zsh
 ~ echo $ZSH_VERSION 
   5.8.1
 ~ antidote -v
   antidote version 1.7.3
```
Despite the errors, the plugins still work. Not a big issue, since antidote still works, but a bit confusing.

**Comment by mattmc3** [comment]
Thank you for reporting back, and for your patience. Right now, 1.7.3 only supports paths beginning with / or ~. If you replace $ZDOTDIR with ~/path/to/zdotdir does it work properly? I have been using `envsubst` for my config to handle vars like $ZDOTDIR, but honestly, antidote should just support variables natively. I’ll see if I can get that feature out today.

**Comment by razvanazamfirei** [comment]
My bad, I missed responding to this. It worked with /Users/username/path/to/zdotdir. I did not try it with ~/path/to/zdotdir, but I assume it would've worked fine. I tested 1.7.4 and using the $ZDOTDIR var works great. Thank you again for your work on this as well as your responsiveness.
